/* ─────────────────────────────────────────────────────────────
   CALM VERITAS — Single source of truth for all articles
   Loaded by: /index.html and /blog/index.html

   When adding new content (daily task):
     1. Add new article entries to the ARTICLES array below
     2. Add new PDF entries to the CHECKLISTS array below
     3. Commit and push — both pages update automatically
   ───────────────────────────────────────────────────────────── */

const ARTICLES = [
  { id:'resistance-training-mental-health', cat:'sport', tag:'Sport', featured:false, title:'Resistance Training and Mental Health: What the Research Shows', excerpt:'Multiple large meta-analyses confirm that resistance training significantly reduces depression and anxiety symptoms. Here is the dose, mechanism, and what distinguishes it from aerobic exercise in the evidence.', date:'June 1, 2026', readTime:'8 min read', badge:null, href:'/blog/resistance-training-mental-health' },
  { id:'caffeine-sleep-timing', cat:'sleep', tag:'Sleep', featured:false, title:'Caffeine and Sleep: What the Half-Life Research Actually Means', excerpt:'Caffeine\'s half-life is 5–7 hours, meaning your afternoon coffee still has pharmacological activity at bedtime. Here is what the science says about timing, adenosine blockade, and how to keep both alertness and sleep quality high.', date:'June 1, 2026', readTime:'7 min read', badge:null, href:'/blog/caffeine-sleep-timing' },
  { id:'circadian-rhythm-light', cat:'sleep', tag:'Sleep', featured:false, title:'Circadian Rhythm and Light: How Photons Control Your Biology', excerpt:'Every cell in your body runs on a roughly 24-hour molecular clock — and light is the dominant signal that keeps all of them synchronized. Here is what the research shows about morning light, evening blue light, and how to use both to optimize sleep and metabolic health.', date:'May 31, 2026', readTime:'8 min read', badge:null, href:'/blog/circadian-rhythm-light' },
  { id:'muscle-protein-synthesis', cat:'health', tag:'Health', featured:false, title:'Muscle Protein Synthesis: What the Evidence Says About Protein, Timing, and Dose', excerpt:'Muscle is the largest organ of glucose disposal in the body and one of the strongest predictors of long-term metabolic health. Here is what the science of muscle protein synthesis actually shows about leucine thresholds, daily protein targets, and why timing matters less than most people think.', date:'May 31, 2026', readTime:'8 min read', badge:null, href:'/blog/muscle-protein-synthesis' },
  { id:'zone-2-training', cat:'sport', tag:'Sport', featured:false, title:'Zone 2 Training: The Science of Low-Intensity Cardio for Fat Burning and Longevity', excerpt:'Endurance coaches have known for decades that elite athletes spend most of their training time going slow. The physiology behind this — mitochondrial biogenesis, fat oxidation, and cardiac remodeling — makes Zone 2 one of the most powerful tools in both performance and longevity research.', date:'May 30, 2026', readTime:'8 min read', badge:null, href:'/blog/zone-2-training-guide' },
  { id:'creatine-guide', cat:'health', tag:'Health', featured:false, title:'Creatine Monohydrate: The Most Evidence-Backed Supplement in Sports Science', excerpt:'Over 500 peer-reviewed studies and three decades of safety data make creatine monohydrate the rare supplement where scientific consensus and popular recommendation actually align. Here is what the evidence shows on dosing, cognitive effects, and what to ignore.', date:'May 30, 2026', readTime:'8 min read', badge:null, href:'/blog/creatine-monohydrate-guide' },
  { id:'vo2-max', cat:'sport', tag:'Sport', featured:false, title:'VO2 Max: The Science of Aerobic Capacity and How to Actually Improve It', excerpt:'VO2 max is the single best physiological predictor of all-cause mortality outside of disease diagnosis. Here\'s what the research says about measuring it, improving it, and why the 80/20 training split is not optional.', date:'May 29, 2026', readTime:'9 min read', badge:null, href:'/blog/vo2-max-training' },
  { id:'omega-3', cat:'health', tag:'Health', featured:false, title:'Omega-3 Fatty Acids: What the Research Supports and What It Doesn\'t', excerpt:'Thousands of trials, genuine signals, and genuine noise. We separate the cardiovascular hype from the real evidence on EPA, DHA, inflammation, and what dose and form the data actually supports.', date:'May 29, 2026', readTime:'8 min read', badge:null, href:'/blog/omega-3-guide' },
  { id:'sleep-cycles', cat:'sleep', tag:'Sleep', featured:true, title:'The Science Behind Sleep Cycles (And Why 8 Hours Isn\'t Always Enough)', excerpt:'Your sleep quality depends less on total hours and more on how many complete 90-minute cycles you finish. Here\'s how to optimize for cycles, not clocks.', date:'May 20, 2026', readTime:'7 min read', href:'/blog/sleep-cycles-science' },
  { id:'box-breathing', cat:'anxiety', tag:'Anxiety', featured:false, title:'Box Breathing: The Evidence Behind the Navy SEAL Technique', excerpt:'A structured breathing protocol used by special operations forces, now backed by peer-reviewed research on anxiety and heart rate variability.', date:'May 21, 2026', readTime:'6 min read', href:'/blog/box-breathing-anxiety' },
  { id:'magnesium', cat:'health', tag:'Health', featured:true, title:'Magnesium Glycinate: What the Research Actually Says', excerpt:'An evidence-based breakdown of the most bioavailable magnesium form, its role in sleep, anxiety, and muscle function, and what dose actually works.', date:'May 22, 2026', readTime:'8 min read', href:'/blog/magnesium-glycinate-guide' },
  { id:'marcus-aurelius', cat:'stoicism', tag:'Stoicism', featured:false, title:'Marcus Aurelius on Mornings: The Stoic Protocol That Still Works', excerpt:'The Roman emperor\'s morning ritual from the Meditations isn\'t mysticism — it\'s a cognitive preparation system that maps directly onto modern evidence.', date:'May 23, 2026', readTime:'7 min read', href:'/blog/marcus-aurelius-morning-practice' },
  { id:'deep-work', cat:'focus', tag:'Focus', featured:false, title:'Deep Work: Cal Newport\'s Framework, and What the Research Adds', excerpt:'Newport\'s concept of cognitively demanding, distraction-free work aligns tightly with neuroscience research on attention — but implementation details matter.', date:'May 24, 2026', readTime:'8 min read', href:'/blog/deep-work-focus-protocol' },
  { id:'vitamin-d', cat:'health', tag:'Health', featured:false, title:'Vitamin D: The Deficiency Most People Don\'t Know They Have', excerpt:'Over 40% of American adults are deficient in vitamin D. Here\'s what the research says about dosing, testing, and why the standard RDA is almost certainly too low.', date:'May 25, 2026', readTime:'7 min read', href:'/blog/vitamin-d-guide' },
  { id:'why-we-sleep', cat:'books', tag:'Books', featured:true, title:'Why We Sleep by Matthew Walker: The Science, the Controversy, and What Holds Up', excerpt:'Walker\'s landmark book changed how millions think about sleep. We separate the solid science from the overclaims — and explain why it\'s still essential reading.', date:'May 26, 2026', readTime:'9 min read', href:'/blog/why-we-sleep-review' },
  { id:'cold-exposure', cat:'health', tag:'Health', featured:false, title:'Cold Exposure: Separating the Evidence from the Hype', excerpt:'Cold showers, ice baths, and cold water immersion have gained enormous cultural momentum. Here\'s what the peer-reviewed research actually supports.', date:'May 27, 2026', readTime:'8 min read', href:'/blog/cold-exposure-recovery' },
  { id:'adenosine-sleep', cat:'sleep', tag:'Sleep', featured:false, title:'Adenosine and Sleep Pressure: The Chemistry That Makes You Tired', excerpt:'Every hour you stay awake, adenosine accumulates in your brain and builds sleep pressure. Understanding this mechanism explains why caffeine works — and why it eventually fails.', date:'May 28, 2026', readTime:'7 min read', href:'/blog/adenosine-sleep-pressure' },
  { id:'cortisol-stress', cat:'anxiety', tag:'Anxiety', featured:false, title:'Cortisol: The Physiology of Chronic Stress and How to Reset the System', excerpt:'Cortisol is not the enemy — dysregulated cortisol is. Here\'s what research shows about the HPA axis, chronic stress physiology, and evidence-based ways to restore balance.', date:'May 28, 2026', readTime:'8 min read', href:'/blog/cortisol-chronic-stress' },
  { id:'pomodoro-focus', cat:'focus', tag:'Focus', featured:false, title:'The Pomodoro Technique: What Neuroscience Says About Timed Work Intervals', excerpt:'Francesco Cirillo\'s 25-minute intervals have helped millions focus. But is the specific timing backed by science? We examine what attention research actually shows.', date:'May 28, 2026', readTime:'7 min read', href:'/blog/pomodoro-focus-technique' },
  { id:'seneca-time', cat:'stoicism', tag:'Stoicism', featured:false, title:'Seneca on Time: The Ancient Warning That\'s More Urgent Than Ever', excerpt:'Two thousand years before the attention economy, Seneca identified exactly how lives are lost — not in dramatic failure but in imperceptible distraction. His Letters are a precision diagnosis.', date:'May 28, 2026', readTime:'8 min read', href:'/blog/seneca-on-time' },
  { id:'four-thousand-weeks', cat:'books', tag:'Books', featured:false, title:'Four Thousand Weeks by Oliver Burkeman: A Rational Case for Embracing Limits', excerpt:'Burkeman argues that productivity culture\'s deepest error is treating finitude as a problem to solve. We examine the philosophy and research behind his counterintuitive argument.', date:'May 28, 2026', readTime:'9 min read', href:'/blog/four-thousand-weeks-review' },
];

const CHECKLISTS = [
  { id:'sleep-checklist', tag:'Checklist', title:'Sleep Hygiene Checklist (PDF)', excerpt:'A printable one-page checklist built from sleep science. Environment, timing, and evening protocol variables that research consistently links to sleep quality.', readTime:'1 page', href:'/checklists/sleep-hygiene-checklist.pdf' },
  { id:'anxiety-checklist', tag:'Checklist', title:'Anxiety Reset Protocol (PDF)', excerpt:'Immediate-use tools and daily maintenance habits. Acute interventions on one side, long-term practices on the other. Evidence-cited.', readTime:'1 page', href:'/checklists/anxiety-protocol.pdf' },
  { id:'cold-checklist', tag:'Checklist', title:'Cold Exposure Protocol (PDF)', excerpt:'Session-by-session checklist for evidence-based cold water immersion. Before, during, and after steps, progression schedule, and the research summary.', readTime:'1 page', href:'/checklists/cold-exposure-checklist.pdf' },
  { id:'stoic-journal', tag:'Guide', title:'Stoic Morning Journal (PDF)', excerpt:'Marcus Aurelius\'s daily practice adapted for modern use. Pre-mortem, memento mori reflection, and a four-virtue evening review. 5-minute protocol.', readTime:'2 pages', href:'/checklists/morning-stoic-journal.pdf' },
  { id:'focus-guide', tag:'Guide', title:'Deep Focus Protocol (PDF)', excerpt:'Environment setup, session structure, and weekly review system for deep work. Based on Newport\'s framework with neuroscience research added.', readTime:'2 pages', href:'/checklists/focus-deep-work-guide.pdf' },
  { id:'supplement-guide', tag:'Guide', title:'Evidence-Based Supplement Guide (PDF)', excerpt:'Three tiers of supplements ranked by evidence quality. Dosing, timing, and what to look for on labels. No brand bias.', readTime:'2 pages', href:'/checklists/supplement-stack-guide.pdf' },
  { id:'cortisol-guide', tag:'Guide', title:'Cortisol Reset Guide (PDF)', excerpt:'HPA axis primer, morning protocol, evidence-ranked interventions (exercise, ashwagandha, MBSR), and what to avoid. Grounded in peer-reviewed stress physiology research.', readTime:'2 pages', href:'/checklists/cortisol-reset-guide.pdf' },
  { id:'strength-checklist', tag:'Checklist', title:'Strength Training Checklist (PDF)', excerpt:'Evidence-based session protocol: pre-session prep, in-session execution, post-workout recovery, and weekly structure. Built from peer-reviewed sports science research.', readTime:'1 page', href:'/checklists/strength-training-checklist.pdf' },
  { id:'hrv-guide', tag:'Guide', title:'HRV-Based Recovery Guide (PDF)', excerpt:'How to measure HRV correctly, interpret your personal baseline, and use daily readiness scores to guide training load. Evidence-ranked interventions that raise HRV and what suppresses it.', readTime:'2 pages', href:'/checklists/hrv-recovery-guide.pdf' },
  { id:'mindfulness-guide', tag:'Guide', title:'Mindfulness Meditation Protocol (PDF)', excerpt:'Two-page evidence-based practice guide covering the MBSR dosing research, session checklists, the neuroscience of structural brain changes, and a minimum viable daily protocol grounded in peer-reviewed studies.', readTime:'2 pages', href:'/checklists/mindfulness-meditation-guide.pdf' },
  { id:'anti-inflammatory-nutrition', tag:'Guide', title:'Anti-Inflammatory Nutrition Guide (PDF)', excerpt:'Two-page evidence-based guide covering key biomarkers, foods that reduce and promote inflammation, a daily checklist, and citations from the PREDIMED trial, JAMA Psychiatry, and Nutrients meta-analyses.', readTime:'2 pages', href:'/checklists/anti-inflammatory-nutrition-guide.pdf' },
];
